import type { Metadata } from 'next'
import { Poppins, Noto_Sans_Bengali } from 'next/font/google'
import './globals.css'
import Head from 'next/head'
import { NextAuthProvider } from './Provider';


const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

const NotoSansBengali = Noto_Sans_Bengali({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-notosansbengali',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: 'Visa App',
  description: 'Generated by create next app',
}

export type OnlyChildrenProps = { children: React.ReactNode }

export default function RootLayout({ children }: OnlyChildrenProps) {
  return (
    <html lang="en" className="bg-gray-50">
      <Head>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet" />
      </Head>
      <NextAuthProvider>
      <body className={[poppins.className].join(" ")}>
        {children}
      </body>
      </NextAuthProvider>
    </html>
  )
}
