import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Visa App',
  description: 'Generated by create next app',
}

export type OnlyChildrenProps = { children: React.ReactNode }

export default function RootLayout({ children }: OnlyChildrenProps) {
  return (
    <html lang="en" className="bg-gray-50">
      <Head>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet" />
      </Head>
      <body className={[inter.className].join(" ")}>
        {children}
      </body>
    </html>
  )
}
